// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL8Tkn1jlNo3fc3_gcZpmcWUBrnA2zxCw',
    appId: '1:800028492561:web:4234bd2ae3f858a8edc2b0',
    messagingSenderId: '800028492561',
    projectId: 'flutter-piscine-2773c',
    authDomain: 'flutter-piscine-2773c.firebaseapp.com',
    storageBucket: 'flutter-piscine-2773c.appspot.com',
    measurementId: 'G-CTWFSJSH3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0wtIUo3TekAvSyHSR-ZHr0XUPGoO9XJc',
    appId: '1:800028492561:android:912ba97ce50c6a27edc2b0',
    messagingSenderId: '800028492561',
    projectId: 'flutter-piscine-2773c',
    storageBucket: 'flutter-piscine-2773c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzOsOZL9_ev_ETM731pS8bTvz2ahPV03k',
    appId: '1:800028492561:ios:cc831d015bd767cdedc2b0',
    messagingSenderId: '800028492561',
    projectId: 'flutter-piscine-2773c',
    storageBucket: 'flutter-piscine-2773c.appspot.com',
    iosClientId: '800028492561-ua21mgrtnfa3r5er727u1mcim69o9vpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.subject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzOsOZL9_ev_ETM731pS8bTvz2ahPV03k',
    appId: '1:800028492561:ios:cc831d015bd767cdedc2b0',
    messagingSenderId: '800028492561',
    projectId: 'flutter-piscine-2773c',
    storageBucket: 'flutter-piscine-2773c.appspot.com',
    iosClientId: '800028492561-ua21mgrtnfa3r5er727u1mcim69o9vpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.subject',
  );
}
